### ISSUE TITLE
Doesn't work with latest version of Electron (v12.0.7)

### ISSUE THREAD

**Issue by ghost** [77Z/electron-local-terminal-prototype#1]
Error message:
```
Uncaught ReferenceError: require is not defined at index.js:1
```

**Comment by 77Z** [comment]
Sorry for the late response, have you tried adding:
`webPreferences: {
    nodeIntegration: true,
    contextIsolation: false
}`
to your BrowserWindow options?

**Comment by ghost** [comment]
This seems to have helped, thanks!
